apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: create-findservice-repo-webhook-run
spec:
  taskRef:
    name: create-webhook
  inputs:
    params:
    - name: GitHubOrg
      value: "meghanaskanagal"
    - name: GitHubUser
      value: "meghanaskanagal"
    - name: GitHubRepo
      value: "find-service"
    - name: GitHubSecretName
      value: webhook-secret
    - name: GitHubAccessTokenKey
      value: token
    - name: GitHubSecretStringKey
      value: secret
    - name: ExternalDomain
      value: #value that we get after creating a event listener
  timeout: 1000s
  serviceAccount: serviceaccount