apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: findservicecicd-listener
spec:
  serviceAccountName: serviceaccount
  triggers:
  - binding:
      name: findservice-cicd-pipelinebinding
    template:
      name: findservice-cicd-triggertemplate
