apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: findservice-cicd-triggertemplate
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: namespace
    description: The namespace to create the resources
  - name: gitrepositoryname
    description: The name of the deployment to be created / patched
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: source-repo-$(params.gitrepositoryname)-$(uid)
      namespace: $(params.namespace)
    spec:
      type: git
      params:
      - name: revision
        value: $(params.gitrevision)
      - name: url
        value: $(params.gitrepositoryurl)
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: image-source-$(params.gitrepositoryname)-$(uid)
      namespace: $(params.namespace)
    spec:
      type: image
      params:
      - name: url
        value: quay.io/meghanaskanagal/$(params.gitrepositoryname):latest
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: findservice-cicd-$(params.gitrepositoryname)-$(uid)
      namespace: $(params.namespace)
    spec:
      pipelineRef:
        name: build-and-deploy
      serviceAccount: 'pipeline'
      resources:
      - name: source-repo
        resourceRef:
          name: source-repo-$(params.gitrepositoryname)-$(uid)
      - name: image-resource
        resourceRef:
          name: image-source-$(params.gitrepositoryname)-$(uid)
      params:
      - name: deployment-name
        value: $(params.gitrepositoryname)

