apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: backend
  namespace: find-my-relative
spec:
  template:
    spec:
      containers:
        - image: quay.io/sm43/backend:latest
          envFrom:
            - configMapRef:
                name: erd-urls
