apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: find-service
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/user1-er-demo/user1-find-service:latest
          env:
            - name: quarkus.kubernetes-config.config-maps
              value: find-service
            - name: quarkus.kubernetes-config.enabled
              value: 'true'
