apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: find-service
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/user1-er-demo/user1-find-service:latest
          volumeMounts:
          - mountPath: /deployments/config
            name: config
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: application.properties
            path: application.properties
          name: find-service
        name: config
       
