apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: build-deploy-ui-pipelinerun
spec:
  pipelineRef:
    name: build-and-deploy
  resources:
  - name: source-repo
    resourceRef:
      name: find-ui-git-repo
  - name: image-resource
    resourceRef:
      name: find-ui-image
  params:
  - name: deployment-name
    value: find-service-frontend